"use client";
import {useState} from "react";
const calUrl="https://cal.com/samad-khader-3neg6z/myspinemd";
const areas=[
{name:"Neck",desc:"Pain, stiffness, or headaches",conditions:["Cervical disc","Spinal stenosis","Muscle strain"]},
{name:"Shoulder / Arm",desc:"Aching, tingling, or weakness",conditions:["Radiculopathy","Nerve irritation","Disc herniation"]},
{name:"Upper Back",desc:"Tightness or pain between the shoulders",conditions:["Thoracic pain","Muscle strain","Postural pain"]},
{name:"Lower Back",desc:"Central or one-sided low back pain",conditions:["Herniated disc","Spinal stenosis","Degenerative disc disease"]},
{name:"Hip",desc:"Pain around the hip or buttock",conditions:["Referred pain","SI joint pain","Nerve irritation"]},
{name:"Leg",desc:"Pain that travels below the hip",conditions:["Sciatica","Radiculopathy","Spinal stenosis"]},
];
export default function Home(){const [selected,setSelected]=useState(3);const a=areas[selected];return <main>
<header><a className="brand" href="/">M <span>MySpineMD</span></a><nav><a href="#explore">Explore pain</a><a href="#approach">Our approach</a><a href="#appointment">Appointment</a></nav></header>
<section className="hero"><p className="eyebrow">EVIDENCE-LED SPINE CARE · DFW</p><h1>Move without fear.<br/><em>Live without spine pain.</em></h1><p>Personalized spine care built around one goal: helping you move forward with clarity. Conservative treatment first. Surgery only when it makes sense.</p><div className="actions"><a className="primary" href="#appointment">Request appointment →</a><a href="#explore">Explore your pain →</a></div></section>
<section id="explore" className="explorer"><div className="explore-head"><p className="eyebrow">MYSPINE EXPLORER</p><h2>Where does it hurt?</h2><p>Start with what you feel—not a medical term. Choose a region to explore common symptom patterns.</p></div><div className="explorer-shell"><div className="area-list">{areas.map((x,i)=><button key={x.name} className={selected===i?"active":""} onClick={()=>setSelected(i)}><span>0{i+1}</span><div><strong>{x.name}</strong><small>{x.desc}</small></div><b>›</b></button>)}</div><div className="body-panel"><div className="body-title">BACK VIEW · SELECT A REGION</div><div className="body-map"><div className="silhouette"><div className="head"/><div className="neck"/><div className="torso"/><div className="arm left"/><div className="arm right"/><div className="leg left"/><div className="leg right"/><div className={"hotspot h"+selected}/></div></div><div className="result"><p className="eyebrow">YOU SELECTED</p><h3>{a.name}</h3><p>{a.desc}</p><div className="chips">{a.conditions.map(c=><span key={c}>{c}</span>)}</div></div></div></div><p className="medical-note"><strong>Educational, not a diagnosis.</strong> The highlighted area shows a general symptom region. A clinical evaluation is the right way to understand your symptoms.</p></section>
<section id="approach" className="dark"><p className="eyebrow">OUR PHILOSOPHY</p><h2>The least invasive path that helps you move forward.</h2><div className="steps"><div><b>01</b><h3>Listen & understand</h3><p>Your symptoms, lifestyle, imaging, and priorities shape the plan.</p></div><div><b>02</b><h3>Start conservatively</h3><p>Care may include activity changes, therapy, medication, or targeted interventions.</p></div><div><b>03</b><h3>Reassess together</h3><p>We explain the options clearly, including when surgery may or may not help.</p></div></div></section>
<section id="appointment" className="appointment"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Let’s find your next step.</h2><p>Demo scheduling only. Please do not enter medical details, insurance information, or other sensitive health information.</p><div className="cal"><iframe src={calUrl} title="Schedule a MySpineMD appointment"/></div><p className="fallback">Calendar not loading? <a href={calUrl} target="_blank" rel="noreferrer">Open the scheduler →</a></p></section>
<footer><strong>MySpineMD</strong><p>Educational information only. Not medical advice or a substitute for professional care.</p><p>© 2026 MySpineMD</p></footer></main>}