"use client";
import {useState} from "react";
const CAL="https://cal.com/samad-khader-3neg6z/myspinemd";

const areas=[
["Neck","Pain, stiffness, or headaches",["Cervical disc","Spinal stenosis","Muscle strain"]],
["Shoulder / Arm","Aching, tingling, or weakness",["Radiculopathy","Nerve irritation","Disc herniation"]],
["Upper Back","Tightness or pain between the shoulders",["Thoracic pain","Muscle strain","Postural pain"]],
["Lower Back","Central or one-sided low back pain",["Herniated disc","Spinal stenosis","Degenerative disc disease"]],
["Hip","Pain around the hip or buttock",["Referred pain","SI joint pain","Nerve irritation"]],
["Leg","Pain that travels below the hip",["Sciatica","Radiculopathy","Spinal stenosis"]]
];
export default function Home(){const [sel,setSel]=useState(3);const a=areas[sel];return <main>
<header className="site-header"><a className="brand" href="/"><span className="brand-mark">M</span><span>MySpineMD</span></a><nav><a href="#explorer">Explore pain</a><a href="#conditions">Conditions</a><a href="#approach">Our approach</a><a href="#physician">Dr. Kesani</a></nav><a href="#appointment" className="nav-cta">Request appointment →</a></header>
<section className="hero"><div className="hero-copy"><p className="eyebrow">Evidence-led spine care · DFW</p><h1>Move without fear.<br/><span>Live without spine pain.</span></h1><p className="hero-lede">Personalized spine care built around one goal: helping you move forward with clarity. Conservative treatment first. Surgery only when it makes sense.</p><div className="hero-actions"><a className="button primary" href="#appointment">Request appointment →</a><a className="button secondary" href="#explorer">Explore your pain →</a></div><div className="hero-proof"><span>✓ Board-certified spine surgeon</span><span>✓ Conservative-care-first</span></div></div><div className="hero-visual"><div className="orb one"/><div className="orb two"/><div className="spine-line">{Array.from({length:14}).map((_,i)=><i key={i}/>)}</div><div className="visual-caption"><span>Designed around you</span><strong>A clearer path back to movement.</strong></div></div></section>
<section className="trust-strip"><p>Listen first.</p><p>Explain clearly.</p><p>Treat thoughtfully.</p></section>
<section className="explorer-section" id="explorer"><div className="section-heading"><p className="eyebrow">MySpine Explorer</p><h2>Where does it hurt?</h2><p>Start with what you feel—not a medical term. Choose from the list or tap directly on the body to explore common symptom patterns.</p></div><div className="explorer-shell"><div className="area-list">{areas.map((x,i)=><button key={x[0] as string} className={sel===i?"active":""} onClick={()=>setSel(i)}><span>0{i+1}</span><div><strong>{x[0] as string}</strong><small>{x[1] as string}</small></div><b>›</b></button>)}</div><div className="explorer-display"><div className="view-label">BACK VIEW · TAP A REGION</div><div className="anatomy-map"><div className="anatomy-figure" aria-label="Back view anatomical figure showing the spine and major body regions"><div className="a-head"/><div className="a-neck"/><div className="a-torso"/><div className="a-arm left"/><div className="a-arm right"/><div className="a-leg left"/><div className="a-leg right"/><div className="a-spine">{Array.from({length:16}).map((_,i)=><i key={i}/>)}</div></div>{areas.map((x,i)=><button key={x[0] as string} className={"body-region r"+i+(sel===i?" active":"")} onClick={()=>setSel(i)} aria-label={"Select "+x[0]} />)}</div><div className="result-card"><p className="eyebrow">You selected</p><h3>{a[0] as string}</h3><p>{a[1] as string}</p><div className="chips">{(a[2] as string[]).map(c=><span key={c}>{c}</span>)}</div></div></div></div><p className="medical-note"><strong>This is educational, not a diagnosis.</strong> The highlighted area shows a general symptom region, not the source of pain. A clinical evaluation is the right way to understand yours.</p></section>
<section className="education" id="conditions"><div className="section-heading light"><p className="eyebrow">Understand what may be happening</p><h2>Complex anatomy.<br/>Made clear.</h2></div><div className="condition-grid">{[["Herniated disc","When disc material extends beyond its usual boundary, it can irritate a nearby nerve.","herniated-disc"],["Spinal stenosis","A narrowing around the spinal canal or nerves that may contribute to pain, numbness, or weakness.","spinal-stenosis"],["Sciatica & radiculopathy","Symptoms can travel along an irritated nerve—from the low back into the hip, leg, or foot.","sciatica"],["Degenerative disc disease","Age-related disc changes are common; treatment depends on symptoms, function, and exam findings.","degenerative-disc-disease"]].map((x,i)=><a className="condition-card" href={"/conditions/"+x[2]} key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><b>Learn more →</b></a>)}</div></section>
<section className="approach" id="approach"><div><p className="eyebrow">Our philosophy</p><h2>The least invasive path that helps you move forward.</h2><p>Most spine problems do not begin with surgery. We start by understanding your story, reviewing the evidence, and building a plan around your goals.</p></div><ol className="journey"><li><span>01</span><div><h3>Listen & understand</h3><p>Your symptoms, lifestyle, imaging, and priorities shape the plan.</p></div></li><li><span>02</span><div><h3>Start conservatively</h3><p>When appropriate, care may include activity changes, therapy, medication, or targeted interventions.</p></div></li><li><span>03</span><div><h3>Reassess together</h3><p>If symptoms persist, we explain the options clearly—including when surgery may or may not help.</p></div></li></ol></section>
<section className="physician" id="physician"><div className="physician-portrait"><div className="portrait-monogram">AK</div><div className="portrait-label">Anil Kesani, MD<br/><span>Orthopedic spine surgeon</span></div></div><div className="physician-copy"><p className="eyebrow">Expertise with perspective</p><h2>Care that sees the whole person—not just the scan.</h2><p>Dr. Anil Kesani combines surgical expertise with a measured, conservative-first philosophy. Each recommendation is grounded in your symptoms, your function, and the life you want to return to.</p><div className="credentials"><span><strong>Fellowship-trained</strong>Spine surgery</span><span><strong>Research-driven</strong>Evidence-led decisions</span><span><strong>Patient-centered</strong>Clear, personal care</span></div></div></section>
<section className="stories"><p className="eyebrow">Patient perspective</p><blockquote>“I finally understood what was causing my pain—and what we could do about it.”</blockquote><p>Illustrative sentiment. Individual experiences and outcomes vary.</p></section>
<section className="appointment" id="appointment"><div><p className="eyebrow">Ready when you are</p><h2>Let’s find your next step.</h2><p>Choose a time below for this demo. Please do not enter medical details, insurance information, or other sensitive health information.</p></div><div className="cal"><iframe src={CAL} title="Schedule a MySpineMD appointment"/></div><p className="fallback">Calendar not loading? <a href={CAL} target="_blank" rel="noreferrer">Open the scheduler →</a></p></section>
<footer><a className="brand" href="/"><span className="brand-mark">M</span><span>MySpineMD</span></a><p>Educational information only. Not medical advice or a substitute for professional care.</p><p>© 2026 MySpineMD</p></footer>
</main>}